#!/usr/bin/env bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

# Update functions
update_cpu() {
  cpu=$(awk '{print $1}' /proc/loadavg)
}

update_memory() {
  memory=$(free -h | awk 'NR==2 {print $3}')
}

update_time() {
  time=$(date "+%b %d %H:%M ")
}

update_weather() {
  weather=$(curl -s "wttr.in/dallas?format=1" | cut -c1)
}

update_vol() {
  vol=" $(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
}

# Set up signal handlers
trap "update_vol; display" "RTMIN"
trap "update_backlight; display" "RTMIN+1"
trap "update_bat; display" "RTMIN+2"

# Initial updates
update_vol

# Main loop
while true; do
  sleep 1
  sec=$((sec + 1))
  case $((sec % 60)) in
    0) update_cpu
      update_memory
      update_time
      update_vol
      ;;
  esac
done

