#! /bin/sh

# Autostart

## Layout do teclado
setxkbmap -layout us -variant intl &

## Compositor do ambiente
picom --config ~/.config/picom/picom.conf &

## Pano de fundo da área de trabalho sempre mudando
## Preserva com nitrogem e muda com o feh
nitrogen --restore &
feh --randomize --no-fehbg --bg-fill /home/erico/Pictures/backgrounds/ &

## Define explicitamente o tema e o tamanho do cursor
export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=24
xsetroot -cursor_name left_ptr

## Atallhos do teclado
sxhkd &

## Script para desconectar e conectar novamente o Echo Pop
bash ~/.config/bspwm/conectar_echo_pop.sh &

## Som
pipewire&

## Bluetooth ativado
bluetoothctl power on &

## Notificações
dunst &

## Polybar
bash ~/.config/polybar/launch.sh --forest >> ~/.polybar.log 2>&1 &

## Rede
nm-applet &

## Captura de tela
flameshot &

## Controlar bluetooth
blueman-applet &

## Evitar que a tela desligue
xset s off -dpms s noblank &

# Comandos do BSPWM
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 2
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 3
bspc config left_padding 3
bspc config single_monocle false

## BSPWM coloring
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"
