#! /bin/bash

# Autostart
# set up the two monitors for bspwm
# NOTE This is a simplistic approach because I already know the settings I
# want to apply.

# Terminate already running bar instances
pkill -9 polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar
# polybar top &
polybar -q main -c "~/.config/polybar/forest/config.ini" &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1-0')
if [[ $my_laptop_external_monitor = *connected* ]]; then
     xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 1920x1080 --rotate normal --right-of eDP-1
#    polybar external &
polybar -q externo -c "~/.config/polybar/forest/config.ini" &
fi


#xrandr --output eDP-1 --off --output HDMI-1-0 --primary --mode 19x1080 --rotate normal
setxkbmap -layout us -variant intl &
# compton --backend glx --vsync opengl-swc &
picom &
# feh --randomize --no-fehbg --bg-fill /home/erico/Imagens/backgrounds/ &
nitrogen --restore &
xsetroot -cursor_name left_ptr
#xfce4-panel -d &
#xfdesktop -D &
sxhkd &
pipewire &
bluetoothctl power on &
dunst &
#bash ~/.config/polybar/launch.sh --forest &
# pkill polybar &
# polybar &
nm-applet &
#xfce4-power-manager &
blueman-applet &
flameshot &
#emacs --daemon&
xset s off -dpms s noblank &

#bspc monitor HDMI-1-0 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP-1 -d I II III IV V 
bspc monitor HDMI-1-0 -d VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 3
bspc config left_padding 3
bspc config single_monocle false

##### BSPWM coloring ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

#bspc rule -a xfce4-panel state=floating border=off &
#bspc rule -a xfce4-popup-whiskermenu state=floating border=off &
#bspc rule -a Whisker\ Menu state=floating border=off &
#bspc rule -a Wrapper-2.0 state=floating border=off focus=on&
#sleep 5 && xprop -name "Whisker Menu"
