#! /bin/sh

# Autostart
setxkbmap -layout us -variant intl &
compton --backend glx --vsync opengl-swc &
# feh --randomize --no-fehbg --bg-fill /home/erico/Imagens/backgrounds/ &
nitrogen --restore &
xsetroot -cursor_name left_ptr
#xfce4-panel -d &
#xfdesktop -D &
sxhkd &
# pipewire&
# bluetoothctl power on &
dunst &
bash ~/.config/polybar/launch.sh --forest &
#nm-applet &
#xfce4-power-manager &
flameshot &
blueman-applet &
#emacs --daemon&
xset s off -dpms s noblank &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 2

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config top_padding 0
bspc config bottom_padding 0
bspc config right_padding 3
bspc config left_padding 3
bspc config single_monocle false

##### BSPWM coloring ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

#bspc rule -a xfce4-panel state=floating border=off &
#bspc rule -a xfce4-popup-whiskermenu state=floating border=off &
#bspc rule -a Whisker\ Menu state=floating border=off &
#bspc rule -a Wrapper-2.0 state=floating border=off focus=on&
#sleep 5 && xprop -name "Whisker Menu"
